### ISSUE TITLE
Possibilities of using other DB than Hive by overriding the local adapter

### ISSUE THREAD

**Issue by Nikhileshwar96** [flutterdata/flutter_data#255] opened 2024-01-04 07:11 UTC
Hi @frank06 ,

I was checking on possibilities on using an alternative DB for Hive. I'm trying this due the following issue: 

[Querying & Sorting](https://github.com/flutterdata/flutter_data/issues/76#issuecomment-1542148861)

The App in which I tried using Hive has heavy dependence in querying and pagination. (i.e., Search and notifications with counts as primary necessity).

The actual issue I face with Hive are
- Limitation in querying directly in the DB layer instead of fetching all data from DB and then querying.
- Limitations in getting the count of a specify table with filters (query).
- Limitation in sorting of data fetched from DB directly instead of fetching all data and sorting.

I came across this [reddit thread](https://www.reddit.com/r/FlutterDev/comments/ul0bqu/comment/iauxpjp/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button), where possibility of overriding Hive using LoaclAdapter was termed possible in future. 

Is it still in your pipeline?

Could you please suggest a way to override Hive if possible?

**Comment by frank06** [comment] 2024-01-25 20:07
Yes! I'm currently working on a branch to make FD run on Objectbox, which I think can definitely help in your case. It's still a few weeks/months away but coming along nicely.

Unfortunately I won't support other dbs for the time being.

**Comment by frank06** [comment] 2024-01-25 20:16
Duplicate of #223

**Closed by frank06** 2024-01-25 20:16 UTC

**Comment by Nikhileshwar96** [comment] 2024-01-29 07:48
Checked out ObjectBox. It's promising.  :)

Just curious as I'm also trying out Isar. You mentioned Hive and Isar being risky. Do you mean Risky to implement in FD?

**Comment by frank06** [comment] 2024-01-29 15:42
@Nikhileshwar96 no, the maintainer is very unpredictable

**Comment by Nikhileshwar96** [comment] 2024-01-30 10:36
> @Nikhileshwar96 no, the maintainer is very unpredictable

Oh ok got it

**Comment by ccfiel** [comment] 2024-03-23 03:13
any update on this? :)

**Comment by frank06** [comment] 2024-04-05 19:49
@ccfiel Very busy so it's going slow but making progress: https://github.com/flutterdata/flutter_data/tree/objectbox

The idea is to have OB as default but I'm making significant changes that will allow plugging something like https://pub.dev/packages/sqlite3 or any other fast store that has sync APIs
